# Generated by Django 5.0.4 on 2024-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_name1', models.CharField(max_length=20)),
                ('lift_name2', models.CharField(max_length=20)),
                ('lift_no', models.IntegerField()),
                ('floor_no', models.IntegerField(max_length=30)),
                ('time_lift1', models.IntegerField()),
                ('time_lift2', models.IntegerField()),
                ('trigger1', models.IntegerField()),
                ('trigger2', models.IntegerField()),
            ],
        ),
    ]
